import nodemailer from 'nodemailer'
import { formatMoney } from '@/lib/money'
import { Client, Invoice } from '@/lib/types'

function splitList(value: string | undefined): string[] {
  return (value ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
}

export function isEmailConfigured(): boolean {
  return Boolean(process.env.EMAIL_HOST && process.env.EMAIL_USER && splitList(process.env.EMAIL_TO).length)
}

function createTransport() {
  return nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: Number(process.env.EMAIL_PORT ?? 587),
    secure: process.env.EMAIL_SECURE === 'true',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASSWORD,
    },
  })
}

function clientAddress(client: Client): string {
  return [client.address_line1, client.address_line2, client.city, client.state, client.postal_code, client.country]
    .filter(Boolean)
    .join(', ')
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export interface InvoiceEmailPayload {
  invoice: Invoice
  client: Client
  pdf: Buffer
  filename: string
  generatedBy: string | null
}

export async function sendInvoiceGeneratedEmail({ invoice, client, pdf, filename, generatedBy }: InvoiceEmailPayload) {
  if (!isEmailConfigured()) {
    console.warn('Email not configured (EMAIL_HOST / EMAIL_USER / EMAIL_TO missing) — skipping invoice notification')
    return
  }

  const number = invoice.invoice_number ?? 'DRAFT'
  const total = `${formatMoney(Number(invoice.total), invoice.currency)} ${invoice.currency}`
  const address = clientAddress(client)

  const rows: [string, string][] = [
    ['Invoice number', number],
    ['Client', client.name],
    ...(client.email ? ([['Client email', client.email]] as [string, string][]) : []),
    ...(client.phone ? ([['Client phone', client.phone]] as [string, string][]) : []),
    ...(address ? ([['Client address', address]] as [string, string][]) : []),
    ['Issue date', invoice.issue_date],
    ['Amount', total],
    ['Generated by', generatedBy ?? 'Unknown'],
  ]

  const html = `
    <div style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #18181b;">
      <p>A new invoice <strong>${escapeHtml(number)}</strong> has been generated for <strong>${escapeHtml(client.name)}</strong>. The PDF is attached.</p>
      <table style="border-collapse: collapse; margin-top: 12px;">
        ${rows
          .map(
            ([label, value]) => `
        <tr>
          <td style="padding: 6px 16px 6px 0; color: #71717a; white-space: nowrap; vertical-align: top;">${escapeHtml(label)}</td>
          <td style="padding: 6px 0;">${escapeHtml(value)}</td>
        </tr>`
          )
          .join('')}
      </table>
    </div>`

  const text = [`A new invoice ${number} has been generated for ${client.name}. The PDF is attached.`, '']
    .concat(rows.map(([label, value]) => `${label}: ${value}`))
    .join('\n')

  await createTransport().sendMail({
    from: process.env.EMAIL_FROM ?? process.env.EMAIL_USER,
    to: splitList(process.env.EMAIL_TO),
    cc: splitList(process.env.EMAIL_CC),
    subject: `Invoice ${number} generated for ${client.name} — ${total}`,
    html,
    text,
    attachments: [{ filename, content: pdf, contentType: 'application/pdf' }],
  })
}
